<a href="https://colab.research.google.com/github/Prerana6210/Data-Science-Practical/blob/main/pract1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
array1=np.array([1,2,3,4,5,6])
print("original array",array1)

original array [1 2 3 4 5 6]


In [27]:
arr=np.array([[1,2,3,4],
             [4,5,6,7],
             [7,8,9,10],
             [10,11,12,13]])
print("original",arr)

swap_rows=arr[::-1,::1]
print("swap_rows",swap_rows)

swap_columns=arr[::-1,::-1]
print("swap_columns",swap_columns)

original [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [10 11 12 13]]
swap_rows [[10 11 12 13]
 [ 7  8  9 10]
 [ 4  5  6  7]
 [ 1  2  3  4]]
swap_columns [[13 12 11 10]
 [10  9  8  7]
 [ 7  6  5  4]
 [ 4  3  2  1]]


In [37]:
swap_columns=arr[0::,::-2]
print("swap_columns",swap_columns)

swap_columns [[ 4  2]
 [ 7  5]
 [10  8]
 [13 11]]


In [42]:
arr[:,[0,2]]=arr[:,[2,0]]
arr

array([[ 3,  2,  1,  4],
       [ 6,  5,  4,  7],
       [ 9,  8,  7, 10],
       [12, 11, 10, 13]])